# types.rs enums
types_lines = []
types_lines.append('use serde::{Deserialize, Serialize};')
types_lines.append('')
types_lines.append('#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]')
types_lines.append('#[serde(rename_all = "snake_case")]')
types_lines.append('pub enum SkillCategory { ToolGuide, Workflow, Reference }')
types_lines.append('impl Default for SkillCategory { fn default() -> Self { Self::Workflow } }')
types_lines.append('')
types_lines.append('impl std::fmt::Display for SkillCategory {')
types_lines.append("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {")
types_lines.append('        match self {')
types_lines.append('            Self::ToolGuide => write!(f, "tool_guide"),')
types_lines.append('            Self::Workflow => write!(f, "workflow"),')
types_lines.append('            Self::Reference => write!(f, "reference"),')
types_lines.append('        }')
types_lines.append('    }')
types_lines.append('}')
types_lines.append('')
types_lines.append('impl std::str::FromStr for SkillCategory {')
types_lines.append('    type Err = crate::EngError;')
types_lines.append('    fn from_str(s: &str) -> std::result::Result<Self, Self::Err> {')
types_lines.append('        match s {')
types_lines.append('            "tool_guide" => Ok(Self::ToolGuide),')
types_lines.append('            "workflow" => Ok(Self::Workflow),')
types_lines.append('            "reference" => Ok(Self::Reference),')
types_lines.append('            _ => Err(crate::EngError::InvalidInput(format!("unknown skill category: {}", s))),')
types_lines.append('        }')
types_lines.append('    }')
types_lines.append('}')
