use axum::{routing::get, Json, Router};
use serde_json::{json, Map, Value};

use crate::state::AppState;

pub fn router() -> Router<AppState> {
    Router::new()
        .route("/openapi.json", get(openapi))
        .route("/docs/openapi.json", get(openapi))
}

async fn openapi() -> Json<Value> {
    Json(build_openapi_spec())
}

fn build_openapi_spec() -> Value {
    let mut paths = Map::new();
    for (path, methods, summary, tag) in route_specs() {
        let mut item = Map::new();
        for method in methods.iter() {
            item.insert(
                (*method).to_string(),
                json!({
                    "summary": summary,
                    "tags": [tag],
                    "responses": {
                        "200": { "description": "Successful response" }
                    }
                }),
            );
        }
        paths.insert(path.to_string(), Value::Object(item));
    }

    json!({
        "openapi": "3.1.0",
        "info": {
            "title": "Engram Memory API",
            "version": env!("CARGO_PKG_VERSION"),
            "description": "OpenAPI surface for the current Rust server routes."
        },
        "servers": [{ "url": "/" }],
        "paths": paths,
    })
}

fn route_specs() -> &'static [(&'static str, &'static [&'static str], &'static str, &'static str)] {
    &[
        ("/health", &["get"], "Health check", "System"),
        ("/live", &["get"], "Liveness check", "System"),
        ("/ready", &["get"], "Readiness check", "System"),
        ("/openapi.json", &["get"], "OpenAPI specification", "Docs"),
        ("/docs/openapi.json", &["get"], "OpenAPI specification", "Docs"),
        ("/store", &["post"], "Store memory", "Memory"),
        ("/memory", &["post"], "Store memory", "Memory"),
        ("/memories", &["post"], "Store memory", "Memory"),
        ("/search", &["post"], "Search memories", "Memory"),
        ("/memories/search", &["post"], "Search memories", "Memory"),
        ("/recall", &["post"], "Recall memories", "Memory"),
        ("/list", &["get"], "List memories", "Memory"),
        ("/tags", &["get"], "List memory tags", "Memory"),
        ("/tags/search", &["post"], "Search memories by tags", "Memory"),
        ("/profile", &["get"], "Get user profile", "Memory"),
        ("/profile/synthesize", &["post"], "Synthesize user profile", "Memory"),
        ("/me/stats", &["get"], "User-scoped stats", "Memory"),
        ("/links/{id}", &["get"], "List memory links", "Memory"),
        ("/versions/{id}", &["get"], "List memory versions", "Memory"),
        ("/memory/{id}", &["get", "delete"], "Read or delete memory", "Memory"),
        ("/memory/{id}/update", &["post"], "Update memory", "Memory"),
        ("/memory/{id}/tags", &["put"], "Replace memory tags", "Memory"),
        ("/memory/{id}/forget", &["post"], "Forget memory", "Memory"),
        ("/memory/{id}/archive", &["post"], "Archive memory", "Memory"),
        ("/memory/{id}/unarchive", &["post"], "Unarchive memory", "Memory"),
        ("/bootstrap", &["post"], "Bootstrap admin user", "Admin"),
        ("/keys", &["get", "post"], "Manage keys", "Auth"),
        ("/keys/{id}", &["delete"], "Revoke key", "Auth"),
        ("/keys/rotate", &["post"], "Rotate key", "Auth"),
        ("/users", &["get", "post"], "Manage users", "Auth"),
        ("/spaces", &["get", "post"], "Manage spaces", "Auth"),
        ("/spaces/{id}", &["delete"], "Delete space", "Auth"),
        ("/stats", &["get"], "Admin stats", "Admin"),
        ("/tasks", &["get", "post"], "Manage tasks", "Tasks"),
        ("/tasks/stats", &["get"], "Task stats", "Tasks"),
        ("/tasks/{id}", &["get", "patch", "delete"], "Read or modify task", "Tasks"),
        ("/feed", &["get"], "Task feed", "Tasks"),
        ("/axon/publish", &["post"], "Publish event", "Axon"),
        ("/axon/events", &["get"], "List events", "Axon"),
        ("/axon/events/{id}", &["get"], "Get event", "Axon"),
        ("/axon/channels", &["get"], "List channels", "Axon"),
        ("/axon/stats", &["get"], "Axon stats", "Axon"),
        ("/broca/actions", &["get", "post"], "Manage Broca actions", "Broca"),
        ("/broca/actions/{id}", &["get"], "Get Broca action", "Broca"),
        ("/broca/feed", &["get"], "Broca feed", "Broca"),
        ("/broca/stats", &["get"], "Broca stats", "Broca"),
        ("/soma/agents", &["get", "post"], "Manage Soma agents", "Soma"),
        ("/soma/agents/{id}", &["get", "patch", "delete"], "Read or modify Soma agent", "Soma"),
        ("/soma/agents/{id}/heartbeat", &["post"], "Record Soma heartbeat", "Soma"),
        ("/soma/stats", &["get"], "Soma stats", "Soma"),
        ("/thymus/goals", &["get", "post"], "Manage goals", "Thymus"),
        ("/thymus/goals/{id}", &["get", "patch", "delete"], "Read or modify goal", "Thymus"),
        ("/thymus/evaluate", &["post"], "Evaluate goal", "Thymus"),
        ("/thymus/evaluations", &["get"], "List evaluations", "Thymus"),
        ("/thymus/evaluations/{id}", &["get"], "Get evaluation", "Thymus"),
        ("/thymus/metrics", &["get", "post"], "Manage metrics", "Thymus"),
        ("/thymus/metrics/summary", &["get"], "Metric summary", "Thymus"),
        ("/thymus/initiatives", &["get", "post"], "Manage initiatives", "Thymus"),
        ("/thymus/initiatives/{id}", &["get", "patch", "delete"], "Read or modify initiative", "Thymus"),
        ("/thymus/stats", &["get"], "Thymus stats", "Thymus"),
        ("/loom/templates", &["get", "post"], "Manage loom templates", "Loom"),
        ("/loom/templates/{id}", &["get", "patch", "delete"], "Read or modify loom template", "Loom"),
        ("/loom/runs", &["get", "post"], "Manage loom runs", "Loom"),
        ("/loom/runs/{id}", &["get"], "Get loom run", "Loom"),
        ("/loom/runs/{id}/cancel", &["post"], "Cancel loom run", "Loom"),
        ("/loom/runs/{id}/steps", &["get"], "List loom steps", "Loom"),
        ("/loom/runs/{id}/logs", &["get"], "List loom logs", "Loom"),
        ("/loom/steps/{id}/complete", &["post"], "Complete loom step", "Loom"),
        ("/loom/steps/{id}/fail", &["post"], "Fail loom step", "Loom"),
        ("/loom/stats", &["get"], "Loom stats", "Loom"),
        ("/episodes", &["get", "post"], "Manage episodes", "Episodes"),
        ("/episodes/{id}", &["get", "patch"], "Read or update episode", "Episodes"),
        ("/episodes/{id}/memories", &["post"], "Assign memories to episode", "Episodes"),
        ("/episodes/{id}/finalize", &["post"], "Finalize episode", "Episodes"),
        ("/conversations", &["get", "post"], "Manage conversations", "Conversations"),
        ("/conversations/{id}", &["get", "patch", "delete"], "Read or modify conversation", "Conversations"),
        ("/conversations/{id}/messages", &["get", "post"], "Manage conversation messages", "Conversations"),
        ("/conversations/bulk", &["post"], "Bulk insert conversations", "Conversations"),
        ("/conversations/upsert", &["post"], "Upsert conversation", "Conversations"),
        ("/messages/search", &["post"], "Search messages", "Conversations"),
        ("/entities", &["get", "post"], "Manage entities", "Graph"),
        ("/entities/{id}", &["get", "delete"], "Read or delete entity", "Graph"),
        ("/entities/{id}/relationships", &["get"], "List entity relationships", "Graph"),
        ("/entities/{id}/memories", &["get"], "List entity memories", "Graph"),
        ("/entities/{id}/cooccurrences", &["get"], "List entity cooccurrences", "Graph"),
        ("/entity-relationships", &["post"], "Create entity relationship", "Graph"),
        ("/graph/build", &["post"], "Build graph", "Graph"),
        ("/graph/search", &["post"], "Search graph", "Graph"),
        ("/graph/neighborhood/{id}", &["get"], "Graph neighborhood", "Graph"),
        ("/graph/communities", &["post"], "Detect communities", "Graph"),
        ("/graph/communities/{id}/members", &["get"], "Community members", "Graph"),
        ("/graph/communities/stats", &["get"], "Community stats", "Graph"),
        ("/graph/pagerank", &["post"], "Run pagerank", "Graph"),
        ("/graph/cooccurrences/rebuild", &["post"], "Rebuild cooccurrences", "Graph"),
        ("/memory/{id}/entities", &["get"], "Memory entities", "Graph"),
        ("/intelligence/consolidate", &["post"], "Run consolidation", "Intelligence"),
        ("/intelligence/reconsolidate", &["post"], "Run reconsolidation", "Intelligence"),
        ("/intelligence/contradictions", &["post"], "Detect contradictions", "Intelligence"),
        ("/intelligence/contradictions/list", &["get"], "List contradictions", "Intelligence"),
        ("/intelligence/temporal/analyze", &["post"], "Analyze temporal data", "Intelligence"),
        ("/intelligence/temporal/patterns", &["get"], "List temporal patterns", "Intelligence"),
        ("/intelligence/digests", &["get"], "List digests", "Intelligence"),
        ("/intelligence/digests/generate", &["post"], "Generate digest", "Intelligence"),
        ("/intelligence/causal/chains", &["get", "post"], "Manage causal chains", "Intelligence"),
        ("/intelligence/causal/chains/{id}", &["get"], "Get causal chain", "Intelligence"),
        ("/intelligence/causal/links", &["post"], "Add causal link", "Intelligence"),
        ("/skills", &["get", "post"], "Manage skills", "Skills"),
        ("/skills/search", &["post"], "Search skills", "Skills"),
        ("/skills/{id}", &["get", "delete"], "Read or delete skill", "Skills"),
        ("/skills/{id}/update", &["post"], "Update skill", "Skills"),
        ("/skills/{id}/execute", &["post"], "Record skill execution", "Skills"),
        ("/skills/{id}/executions", &["get"], "List skill executions", "Skills"),
        ("/skills/{id}/judge", &["post"], "Judge skill", "Skills"),
        ("/skills/{id}/judgments", &["get"], "List skill judgments", "Skills"),
        ("/skills/{id}/tags", &["get"], "List skill tags", "Skills"),
        ("/skills/{id}/deps", &["get"], "List skill dependencies", "Skills"),
        ("/skills/{id}/lineage", &["get"], "Get skill lineage", "Skills"),
        ("/tools/quality", &["post"], "Record tool quality", "Skills"),
        ("/tools/quality/{tool_name}", &["get"], "Get tool quality", "Skills"),
        ("/skills/dashboard/health", &["get"], "Skills dashboard health", "Skills"),
        ("/skills/dashboard/overview", &["get"], "Skills dashboard overview", "Skills"),
        ("/skills/dashboard/stats", &["get"], "Skills dashboard stats", "Skills"),
        ("/skills/{id}/detail", &["get"], "Get skill detail", "Skills"),
        ("/skills/evolve", &["post"], "Evolve skills", "Skills"),
        ("/skills/{id}/fix", &["post"], "Fix skill", "Skills"),
        ("/skills/derive", &["post"], "Derive skill", "Skills"),
        ("/skills/capture", &["post"], "Capture skill", "Skills"),
        ("/skills/usage-stats", &["get"], "Skill usage stats", "Skills"),
        ("/skills/cloud/search", &["post"], "Search cloud skills", "Skills"),
        ("/skills/cloud/upload", &["post"], "Upload cloud skill", "Skills"),
        ("/personality/detect", &["post"], "Detect personality", "Personality"),
        ("/personality/traits", &["get", "post"], "Manage personality traits", "Personality"),
        ("/personality/profile", &["get"], "Get personality profile", "Personality"),
        ("/personality/profile/update", &["post"], "Update personality profile", "Personality"),
        ("/sync/changes", &["get"], "Get sync changes", "Platform"),
        ("/audit", &["get"], "Audit log", "Security"),
        ("/quota", &["get"], "Quota status", "Security"),
        ("/usage", &["post"], "Record usage", "Security"),
        ("/rate-limit/{key}", &["get"], "Rate limit status", "Security"),
        ("/activity", &["post"], "Report activity", "Activity"),
        ("/gate/check", &["post"], "Gate check", "Gate"),
        ("/gate/respond", &["post"], "Gate respond", "Gate"),
        ("/gate/complete", &["post"], "Gate complete", "Gate"),
        ("/growth/reflect", &["post"], "Growth reflection", "Growth"),
        ("/growth/observations", &["get"], "Growth observations", "Growth"),
        ("/growth/materialize", &["post"], "Growth materialize", "Growth"),
        ("/sessions", &["get", "post"], "Manage sessions", "Sessions"),
        ("/sessions/{id}", &["get"], "Get session", "Sessions"),
        ("/sessions/{id}/append", &["post"], "Append session output", "Sessions"),
        ("/sessions/{id}/stream", &["get"], "Stream session output", "Sessions"),
        ("/agents", &["get", "post"], "Manage agents", "Agents"),
        ("/agents/{id}", &["get"], "Get agent", "Agents"),
        ("/agents/{id}/revoke", &["post"], "Revoke agent", "Agents"),
        ("/agents/{id}/passport", &["get"], "Issue passport", "Agents"),
        ("/agents/{id}/link-key", &["post"], "Link API key to agent", "Agents"),
        ("/agents/{id}/executions", &["get"], "List agent executions", "Agents"),
        ("/verify", &["post"], "Verify signed agent payload", "Agents"),
        ("/artifacts/stats", &["get"], "Artifact stats", "Artifacts"),
        ("/artifacts/{memory_id}", &["get"], "List memory artifacts", "Artifacts"),
        ("/artifact/{id}", &["get"], "Download artifact", "Artifacts"),
        ("/fsrs/review", &["post"], "Process FSRS review", "FSRS"),
        ("/fsrs/state", &["get"], "Get FSRS state", "FSRS"),
        ("/fsrs/init", &["post"], "Backfill FSRS state", "FSRS"),
        ("/grounding/sessions", &["get", "post"], "Manage grounding sessions", "Grounding"),
        ("/grounding/sessions/{id}", &["get", "delete"], "Read or destroy grounding session", "Grounding"),
        ("/grounding/tools", &["get"], "List grounding tools", "Grounding"),
        ("/grounding/execute", &["post"], "Execute grounding tool", "Grounding"),
        ("/grounding/quality", &["get"], "Grounding quality records", "Grounding"),
        ("/grounding/providers", &["get"], "List grounding providers", "Grounding"),
        ("/decay/refresh", &["post"], "Refresh decay scores", "Search"),
        ("/decay/scores", &["get"], "List decay scores", "Search"),
        ("/onboard", &["post"], "Onboard", "Onboard"),
        ("/fetch", &["post"], "Fetch URL", "Onboard"),
        ("/import/bulk", &["post"], "Bulk import", "Ingestion"),
        ("/import/json", &["post"], "Import JSON", "Ingestion"),
        ("/import/mem0", &["post"], "Import mem0", "Ingestion"),
        ("/import/supermemory", &["post"], "Import supermemory", "Ingestion"),
        ("/ingest", &["post"], "Ingest text", "Ingestion"),
        ("/add", &["post"], "Add conversation", "Ingestion"),
        ("/derive", &["post"], "Derive memories", "Ingestion"),
        ("/prompt", &["get"], "Get prompt", "Prompts"),
        ("/prompt/generate", &["post"], "Generate prompt", "Prompts"),
        ("/header", &["post"], "Post header", "Prompts"),
        ("/scratch", &["get", "put"], "Manage scratchpad", "Scratchpad"),
        ("/scratch/{session}", &["delete"], "Delete scratch session", "Scratchpad"),
        ("/scratch/{session}/{key}", &["delete"], "Delete scratch key", "Scratchpad"),
        ("/scratch/{session}/promote", &["post"], "Promote scratch entry", "Scratchpad"),
        ("/inbox", &["get"], "List inbox", "Inbox"),
        ("/inbox/{id}/approve", &["post"], "Approve inbox item", "Inbox"),
        ("/inbox/{id}/reject", &["post"], "Reject inbox item", "Inbox"),
        ("/inbox/{id}/edit", &["post"], "Edit inbox item", "Inbox"),
        ("/inbox/bulk", &["post"], "Bulk inbox action", "Inbox"),
        ("/pending", &["get"], "Legacy pending inbox list", "Inbox"),
        ("/pack", &["post"], "Pack memories", "Pack"),
        ("/projects", &["get", "post"], "Manage projects", "Projects"),
        ("/projects/{id}", &["get", "put", "delete"], "Read or modify project", "Projects"),
        ("/projects/{id}/memories/{mid}", &["put", "delete"], "Link or unlink project memory", "Projects"),
        ("/webhooks", &["get", "post"], "Manage webhooks", "Webhooks"),
        ("/webhooks/{id}", &["get", "put", "delete"], "Read or modify webhook", "Webhooks"),
        ("/webhooks/test/{id}", &["post"], "Test webhook", "Webhooks"),
        ("/brain/stats", &["get"], "Brain stats", "Brain"),
        ("/brain/query", &["post"], "Brain query", "Brain"),
        ("/brain/absorb", &["post"], "Brain absorb", "Brain"),
        ("/brain/dream", &["post"], "Brain dream", "Brain"),
        ("/brain/feedback", &["post"], "Brain feedback", "Brain"),
        ("/brain/decay", &["post"], "Brain decay", "Brain"),
        ("/context", &["post"], "Build context", "Context"),
    ]
}
