//! Route registry. One entry per HTTP route on `kleos-server`. Both the
//! `kleos-mcp` tool list and the runtime dispatcher iterate this slice -- so
//! adding a new route means a single new entry here, nothing else.

use serde_json::Value;

/// HTTP method for a registered route.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Method {
    Get,
    Post,
    Put,
    Delete,
    Patch,
}

/// HTTP-verb formatting for the canonical envelope.
impl Method {
    /// The method as the uppercase HTTP verb string used for signing.
    pub fn as_verb(&self) -> &'static str {
        match self {
            Method::Get => "GET",
            Method::Post => "POST",
            Method::Put => "PUT",
            Method::Delete => "DELETE",
            Method::Patch => "PATCH",
        }
    }
}

/// Required scope on the server side. Surfaced for documentation; the server
/// is the authoritative enforcer.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Scope {
    Read,
    Write,
    Admin,
}

/// One MCP tool == one kleos-server HTTP route.
///
/// `path` is a template; `{name}` segments are filled from the corresponding
/// top-level field of the call arguments before the request goes out, and the
/// field is dropped from the JSON body so it does not duplicate the path.
#[derive(Clone, Copy, Debug)]
pub struct Route {
    /// Canonical tool name, e.g. "memory.store".
    pub name: &'static str,
    /// Back-compat aliases. Same dispatch target.
    pub aliases: &'static [&'static str],
    pub method: Method,
    pub path: &'static str,
    pub scope: Scope,
    pub description: &'static str,
    /// Raw JSON Schema literal for the tool's input. Parsed once at startup.
    pub input_schema: &'static str,
}

/// Walks the registry and returns the route whose canonical name or aliases match.
pub fn find_by_name(name: &str) -> Option<&'static Route> {
    ROUTES.iter().find(|r| r.name == name || r.aliases.contains(&name))
}

/// Substitutes `{key}` segments in the template with values from `args`,
/// removing those keys from `args` so they do not duplicate in the body.
pub fn render_path(template: &str, args: &mut Value) -> Result<String, String> {
    let mut out = String::with_capacity(template.len() + 32);
    let mut rest = template;
    while let Some(open) = rest.find('{') {
        out.push_str(&rest[..open]);
        let after_open = &rest[open + 1..];
        let close = after_open
            .find('}')
            .ok_or_else(|| format!("malformed path template: {template}"))?;
        let key = &after_open[..close];
        let value = args
            .as_object_mut()
            .and_then(|m| m.remove(key))
            .ok_or_else(|| format!("missing path argument '{key}' for template {template}"))?;
        match value {
            Value::String(s) => out.push_str(&s),
            Value::Number(n) => out.push_str(&n.to_string()),
            other => out.push_str(&other.to_string()),
        }
        rest = &after_open[close + 1..];
    }
    out.push_str(rest);
    Ok(out)
}

/// The route registry. Hand-maintained for now; one entry per HTTP route.
///
/// Entries here drive both the MCP `tools/list` payload and the dispatcher.
/// The kleos-cli aliases on memory/skills/etc preserve back-compat with
/// existing MCP client configurations that may reference the old names.
pub static ROUTES: &[Route] = &[
    // -- memory -----------------------------------------------------------
    Route {
        name: "memory.store",
        aliases: &[],
        method: Method::Post,
        path: "/store",
        scope: Scope::Write,
        description: "Store a new memory.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "content": {"type": "string"},
                "category": {"type": "string"},
                "source": {"type": "string"},
                "importance": {"type": "integer"},
                "tags": {"type": "array", "items": {"type": "string"}},
                "session_id": {"type": "string"},
                "is_static": {"type": "boolean"},
                "space_id": {"type": "integer"}
            },
            "required": ["content"]
        }"#,
    },
    Route {
        name: "memory.search",
        aliases: &[],
        method: Method::Post,
        path: "/search",
        scope: Scope::Read,
        description: "Hybrid search across memories.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "query": {"type": "string"},
                "limit": {"type": "integer"},
                "category": {"type": "string"},
                "source": {"type": "string"},
                "tags": {"type": "array", "items": {"type": "string"}},
                "threshold": {"type": "number"},
                "space_id": {"type": "integer"},
                "include_forgotten": {"type": "boolean"},
                "mode": {"type": "string"},
                "question_type": {"type": "string"},
                "expand_relationships": {"type": "boolean"},
                "include_links": {"type": "boolean"},
                "latest_only": {"type": "boolean"},
                "source_filter": {"type": "string"}
            },
            "required": ["query"]
        }"#,
    },
    Route {
        name: "memory.get",
        aliases: &[],
        method: Method::Get,
        path: "/memory/{id}",
        scope: Scope::Read,
        description: "Fetch a memory by id.",
        input_schema: r#"{
            "type": "object",
            "properties": {"id": {"type": "integer"}},
            "required": ["id"]
        }"#,
    },
    Route {
        name: "memory.list",
        aliases: &[],
        method: Method::Get,
        path: "/list",
        scope: Scope::Read,
        description: "Paginated listing of memories.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "limit": {"type": "integer"},
                "offset": {"type": "integer"},
                "category": {"type": "string"},
                "source": {"type": "string"},
                "space_id": {"type": "integer"},
                "include_forgotten": {"type": "boolean"},
                "include_archived": {"type": "boolean"}
            }
        }"#,
    },
    Route {
        name: "memory.update",
        aliases: &[],
        method: Method::Post,
        path: "/memory/{id}/update",
        scope: Scope::Write,
        description: "Update a memory.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "id": {"type": "integer"},
                "content": {"type": "string"},
                "category": {"type": "string"},
                "source": {"type": "string"},
                "importance": {"type": "integer"},
                "tags": {"type": "array", "items": {"type": "string"}},
                "status": {"type": "string"}
            },
            "required": ["id"]
        }"#,
    },
    Route {
        name: "memory.delete",
        aliases: &[],
        method: Method::Delete,
        path: "/memory/{id}",
        scope: Scope::Write,
        description: "Delete a memory.",
        input_schema: r#"{
            "type": "object",
            "properties": {"id": {"type": "integer"}},
            "required": ["id"]
        }"#,
    },
    Route {
        name: "memory.mark_forgotten",
        aliases: &[],
        method: Method::Post,
        path: "/memory/{id}/forget",
        scope: Scope::Write,
        description: "Soft-delete a memory.",
        input_schema: r#"{
            "type": "object",
            "properties": {"id": {"type": "integer"}, "reason": {"type": "string"}},
            "required": ["id"]
        }"#,
    },
    Route {
        name: "memory.mark_archived",
        aliases: &[],
        method: Method::Post,
        path: "/memory/{id}/archive",
        scope: Scope::Write,
        description: "Archive a memory.",
        input_schema: r#"{
            "type": "object",
            "properties": {"id": {"type": "integer"}},
            "required": ["id"]
        }"#,
    },
    Route {
        name: "memory.mark_unarchived",
        aliases: &[],
        method: Method::Post,
        path: "/memory/{id}/unarchive",
        scope: Scope::Write,
        description: "Restore an archived memory.",
        input_schema: r#"{
            "type": "object",
            "properties": {"id": {"type": "integer"}},
            "required": ["id"]
        }"#,
    },
    Route {
        name: "memory.recall",
        aliases: &[],
        method: Method::Post,
        path: "/recall",
        scope: Scope::Read,
        description: "Recall by query, returns ranked memories.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "query": {"type": "string"},
                "limit": {"type": "integer"}
            },
            "required": ["query"]
        }"#,
    },
    // -- skills -----------------------------------------------------------
    Route {
        name: "skill.search",
        aliases: &[],
        method: Method::Post,
        path: "/skills/search",
        scope: Scope::Read,
        description: "Search skill registry.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "query": {"type": "string"},
                "limit": {"type": "integer"},
                "tags": {"type": "array", "items": {"type": "string"}}
            },
            "required": ["query"]
        }"#,
    },
    Route {
        name: "skill.execute",
        aliases: &[],
        method: Method::Post,
        path: "/skills/execute",
        scope: Scope::Read,
        description: "Match skills to a task and return the most relevant skill content.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "task": {"type": "string"},
                "limit": {"type": "integer"}
            },
            "required": ["task"]
        }"#,
    },
    Route {
        name: "skill.upload",
        aliases: &[],
        method: Method::Post,
        path: "/skills/capture",
        scope: Scope::Write,
        description: "Create a new skill record.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "code": {"type": "string"},
                "language": {"type": "string"},
                "tags": {"type": "array", "items": {"type": "string"}},
                "agent": {"type": "string"}
            },
            "required": ["name", "code"]
        }"#,
    },
    Route {
        name: "skill.fix",
        aliases: &[],
        method: Method::Post,
        path: "/skills/{skill_id}/fix",
        scope: Scope::Write,
        description: "Run LLM-driven repair on a skill.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "skill_id": {"type": "integer"},
                "direction": {"type": "string"}
            },
            "required": ["skill_id"]
        }"#,
    },
    // -- activity ---------------------------------------------------------
    Route {
        name: "activity.report",
        aliases: &[],
        method: Method::Post,
        path: "/activity",
        scope: Scope::Write,
        description: "Unified fan-out hub (Chiasm, Axon, Broca, Thymus, Skills, Memory).",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "action": {"type": "string"},
                "summary": {"type": "string"},
                "project": {"type": "string"},
                "agent": {"type": "string"},
                "metadata": {"type": "object"}
            },
            "required": ["action", "summary"]
        }"#,
    },
    // -- health -----------------------------------------------------------
    Route {
        name: "health",
        aliases: &[],
        method: Method::Get,
        path: "/health",
        scope: Scope::Read,
        description: "Server liveness probe.",
        input_schema: r#"{"type": "object"}"#,
    },
    // -- handoffs ---------------------------------------------------------
    Route {
        name: "handoffs.store",
        aliases: &["handoffs.dump"],
        method: Method::Post,
        path: "/handoffs",
        scope: Scope::Write,
        description: "Store a new handoff dump.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "agent": {"type": "string"},
                "handoff_type": {"type": "string"},
                "content": {"type": "string"},
                "metadata": {"type": "object"}
            },
            "required": ["content"]
        }"#,
    },
    Route {
        name: "handoffs.list",
        aliases: &[],
        method: Method::Get,
        path: "/handoffs",
        scope: Scope::Read,
        description: "List handoffs.",
        input_schema: r#"{"type": "object", "properties": {"limit": {"type":"integer"}, "offset": {"type":"integer"}, "agent": {"type":"string"}, "handoff_type": {"type":"string"}}}"#,
    },
    Route {
        name: "handoffs.latest",
        aliases: &[],
        method: Method::Get,
        path: "/handoffs/latest",
        scope: Scope::Read,
        description: "Fetch the most recent handoff.",
        input_schema: r#"{"type": "object", "properties": {"agent": {"type":"string"}, "handoff_type": {"type":"string"}}}"#,
    },
    Route {
        name: "handoffs.search",
        aliases: &[],
        method: Method::Get,
        path: "/handoffs/search",
        scope: Scope::Read,
        description: "Search handoffs by query string.",
        input_schema: r#"{"type": "object", "properties": {"query": {"type":"string"}, "limit": {"type":"integer"}}, "required": ["query"]}"#,
    },
    Route {
        name: "handoffs.stats",
        aliases: &[],
        method: Method::Get,
        path: "/handoffs/stats",
        scope: Scope::Read,
        description: "Aggregate handoff statistics.",
        input_schema: r#"{"type": "object"}"#,
    },
    Route {
        name: "handoffs.gc",
        aliases: &[],
        method: Method::Post,
        path: "/handoffs/gc",
        scope: Scope::Write,
        description: "Garbage-collect old handoffs.",
        input_schema: r#"{"type": "object", "properties": {"tiered": {"type":"boolean"}, "keep": {"type":"integer"}}}"#,
    },
    Route {
        name: "handoffs.delete",
        aliases: &[],
        method: Method::Delete,
        path: "/handoffs/{id}",
        scope: Scope::Write,
        description: "Delete a specific handoff.",
        input_schema: r#"{"type": "object", "properties": {"id": {"type":"integer"}}, "required": ["id"]}"#,
    },
    // -- jobs -------------------------------------------------------------
    Route {
        name: "jobs.list",
        aliases: &[],
        method: Method::Get,
        path: "/jobs",
        scope: Scope::Read,
        description: "List background jobs.",
        input_schema: r#"{"type": "object", "properties": {"limit": {"type":"integer"}, "status": {"type":"string"}}}"#,
    },
    Route {
        name: "jobs.pending",
        aliases: &[],
        method: Method::Get,
        path: "/jobs/pending",
        scope: Scope::Read,
        description: "List pending jobs.",
        input_schema: r#"{"type": "object"}"#,
    },
    Route {
        name: "jobs.running",
        aliases: &[],
        method: Method::Get,
        path: "/jobs/running",
        scope: Scope::Read,
        description: "List currently running jobs.",
        input_schema: r#"{"type": "object"}"#,
    },
    Route {
        name: "jobs.failed",
        aliases: &[],
        method: Method::Get,
        path: "/jobs/failed",
        scope: Scope::Read,
        description: "List failed jobs.",
        input_schema: r#"{"type": "object"}"#,
    },
    Route {
        name: "jobs.retry",
        aliases: &[],
        method: Method::Post,
        path: "/jobs/retry",
        scope: Scope::Write,
        description: "Retry failed jobs (all matching).",
        input_schema: r#"{"type": "object", "properties": {"all": {"type":"boolean"}, "kind": {"type":"string"}}}"#,
    },
    Route {
        name: "jobs.retry_by_id",
        aliases: &[],
        method: Method::Post,
        path: "/jobs/{id}/retry",
        scope: Scope::Write,
        description: "Retry a specific job by id.",
        input_schema: r#"{"type": "object", "properties": {"id": {"type":"integer"}}, "required": ["id"]}"#,
    },
    Route {
        name: "jobs.purge",
        aliases: &[],
        method: Method::Post,
        path: "/jobs/purge",
        scope: Scope::Admin,
        description: "Permanently remove jobs matching the criteria.",
        input_schema: r#"{"type": "object", "properties": {"status": {"type":"string"}, "before": {"type":"string"}}}"#,
    },
    Route {
        name: "jobs.cleanup",
        aliases: &[],
        method: Method::Post,
        path: "/jobs/cleanup",
        scope: Scope::Admin,
        description: "Garbage-collect completed jobs.",
        input_schema: r#"{"type": "object", "properties": {"keep": {"type":"integer"}}}"#,
    },
    Route {
        name: "jobs.stats",
        aliases: &[],
        method: Method::Get,
        path: "/jobs/stats",
        scope: Scope::Read,
        description: "Job queue statistics.",
        input_schema: r#"{"type": "object"}"#,
    },
    // -- fsrs (spaced repetition) -----------------------------------------
    Route {
        name: "fsrs.review",
        aliases: &[],
        method: Method::Post,
        path: "/fsrs/review",
        scope: Scope::Write,
        description: "Record an FSRS review outcome for a memory.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "memory_id": {"type":"integer"},
                "rating": {"type":"integer", "description":"1=Again, 2=Hard, 3=Good, 4=Easy"}
            },
            "required": ["memory_id", "rating"]
        }"#,
    },
    Route {
        name: "fsrs.state",
        aliases: &[],
        method: Method::Get,
        path: "/fsrs/state",
        scope: Scope::Read,
        description: "Fetch FSRS scheduling state for a memory.",
        input_schema: r#"{"type": "object", "properties": {"memory_id": {"type":"integer"}}, "required": ["memory_id"]}"#,
    },
    Route {
        name: "fsrs.init",
        aliases: &[],
        method: Method::Post,
        path: "/fsrs/init",
        scope: Scope::Admin,
        description: "Backfill FSRS state for existing memories.",
        input_schema: r#"{"type": "object", "properties": {"limit": {"type":"integer"}}}"#,
    },
    Route {
        name: "fsrs.recall_due",
        aliases: &[],
        method: Method::Get,
        path: "/fsrs/recall-due",
        scope: Scope::Read,
        description: "List memories due for spaced-repetition reinforcement.",
        input_schema: r#"{"type": "object", "properties": {"limit": {"type":"integer"}}}"#,
    },
    // -- tasks (chiasm) ---------------------------------------------------
    Route {
        name: "tasks.list",
        aliases: &[],
        method: Method::Get,
        path: "/tasks",
        scope: Scope::Read,
        description: "List Chiasm coordination tasks.",
        input_schema: r#"{"type": "object", "properties": {"agent": {"type":"string"}, "project": {"type":"string"}, "status": {"type":"string"}, "limit": {"type":"integer"}}}"#,
    },
    Route {
        name: "tasks.create",
        aliases: &["services.chiasm_create_task"],
        method: Method::Post,
        path: "/tasks",
        scope: Scope::Write,
        description: "Create a Chiasm coordination task.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "agent": {"type": "string"},
                "project": {"type": "string"},
                "title": {"type": "string"},
                "summary": {"type": "string"},
                "status": {"type": "string"}
            },
            "required": ["agent", "project", "title"]
        }"#,
    },
    Route {
        name: "tasks.stats",
        aliases: &[],
        method: Method::Get,
        path: "/tasks/stats",
        scope: Scope::Read,
        description: "Aggregate task statistics.",
        input_schema: r#"{"type": "object"}"#,
    },
    Route {
        name: "tasks.history",
        aliases: &[],
        method: Method::Get,
        path: "/tasks/{id}/history",
        scope: Scope::Read,
        description: "Task status history.",
        input_schema: r#"{"type": "object", "properties": {"id": {"type":"integer"}}, "required": ["id"]}"#,
    },
    Route {
        name: "tasks.feed",
        aliases: &[],
        method: Method::Get,
        path: "/feed",
        scope: Scope::Read,
        description: "Cross-task activity feed.",
        input_schema: r#"{"type": "object", "properties": {"limit": {"type":"integer"}}}"#,
    },
    // -- sessions ---------------------------------------------------------
    Route {
        name: "sessions.get",
        aliases: &[],
        method: Method::Get,
        path: "/sessions/{id}",
        scope: Scope::Read,
        description: "Fetch a session record.",
        input_schema: r#"{"type": "object", "properties": {"id": {"type":"string"}}, "required": ["id"]}"#,
    },
    Route {
        name: "sessions.append",
        aliases: &[],
        method: Method::Post,
        path: "/sessions/{id}/append",
        scope: Scope::Write,
        description: "Append an entry to a session.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "id": {"type":"string"},
                "role": {"type":"string"},
                "content": {"type":"string"},
                "metadata": {"type":"object"}
            },
            "required": ["id", "content"]
        }"#,
    },
    // -- scratchpad -------------------------------------------------------
    Route {
        name: "scratchpad.list",
        aliases: &[],
        method: Method::Get,
        path: "/scratch",
        scope: Scope::Read,
        description: "List scratchpad entries.",
        input_schema: r#"{"type": "object", "properties": {"session": {"type":"string"}}}"#,
    },
    Route {
        name: "scratchpad.put",
        aliases: &[],
        method: Method::Put,
        path: "/scratch",
        scope: Scope::Write,
        description: "Store or update a scratchpad entry.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "session": {"type":"string"},
                "key": {"type":"string"},
                "value": {}
            },
            "required": ["session", "key", "value"]
        }"#,
    },
    Route {
        name: "scratchpad.delete_session",
        aliases: &[],
        method: Method::Delete,
        path: "/scratch/{session}",
        scope: Scope::Write,
        description: "Delete every scratchpad entry for a session.",
        input_schema: r#"{"type": "object", "properties": {"session": {"type":"string"}}, "required": ["session"]}"#,
    },
    Route {
        name: "scratchpad.delete_key",
        aliases: &[],
        method: Method::Delete,
        path: "/scratch/{session}/{key}",
        scope: Scope::Write,
        description: "Delete a specific scratchpad key.",
        input_schema: r#"{"type": "object", "properties": {"session": {"type":"string"}, "key": {"type":"string"}}, "required": ["session", "key"]}"#,
    },
    Route {
        name: "scratchpad.promote",
        aliases: &[],
        method: Method::Post,
        path: "/scratch/{session}/promote",
        scope: Scope::Write,
        description: "Promote a scratchpad session to durable memory.",
        input_schema: r#"{"type": "object", "properties": {"session": {"type":"string"}}, "required": ["session"]}"#,
    },
    // -- episodes ---------------------------------------------------------
    Route {
        name: "episodes.list",
        aliases: &[],
        method: Method::Get,
        path: "/episodes",
        scope: Scope::Read,
        description: "List episodes.",
        input_schema: r#"{"type": "object", "properties": {"limit": {"type":"integer"}, "offset": {"type":"integer"}}}"#,
    },
    Route {
        name: "episodes.create",
        aliases: &[],
        method: Method::Post,
        path: "/episodes",
        scope: Scope::Write,
        description: "Create a new episode.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "title": {"type":"string"},
                "summary": {"type":"string"},
                "started_at": {"type":"string"},
                "metadata": {"type":"object"}
            },
            "required": ["title"]
        }"#,
    },
    Route {
        name: "episodes.get",
        aliases: &[],
        method: Method::Get,
        path: "/episodes/{id}",
        scope: Scope::Read,
        description: "Fetch one episode by id.",
        input_schema: r#"{"type": "object", "properties": {"id": {"type":"integer"}}, "required": ["id"]}"#,
    },
    Route {
        name: "episodes.update",
        aliases: &[],
        method: Method::Patch,
        path: "/episodes/{id}",
        scope: Scope::Write,
        description: "Update an episode.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "id": {"type":"integer"},
                "title": {"type":"string"},
                "summary": {"type":"string"},
                "metadata": {"type":"object"}
            },
            "required": ["id"]
        }"#,
    },
    Route {
        name: "episodes.assign_memories",
        aliases: &[],
        method: Method::Post,
        path: "/episodes/{id}/memories",
        scope: Scope::Write,
        description: "Attach memories to an episode.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "id": {"type":"integer"},
                "memory_ids": {"type":"array","items":{"type":"integer"}}
            },
            "required": ["id", "memory_ids"]
        }"#,
    },
    Route {
        name: "episodes.finalize",
        aliases: &[],
        method: Method::Post,
        path: "/episodes/{id}/finalize",
        scope: Scope::Write,
        description: "Close an episode and lock its membership.",
        input_schema: r#"{"type": "object", "properties": {"id": {"type":"integer"}}, "required": ["id"]}"#,
    },
    // -- prompts ----------------------------------------------------------
    Route {
        name: "prompts.get",
        aliases: &[],
        method: Method::Get,
        path: "/prompt",
        scope: Scope::Read,
        description: "Fetch the active prompt template.",
        input_schema: r#"{"type": "object", "properties": {"name": {"type":"string"}}}"#,
    },
    Route {
        name: "prompts.generate",
        aliases: &["context.generate_prompt"],
        method: Method::Post,
        path: "/prompt/generate",
        scope: Scope::Read,
        description: "Pack memories into a prompt for a given task.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "task": {"type": "string"},
                "format": {"type": "string"},
                "limit": {"type": "integer"}
            },
            "required": ["task"]
        }"#,
    },
    Route {
        name: "prompts.header",
        aliases: &["context.get_header"],
        method: Method::Post,
        path: "/header",
        scope: Scope::Read,
        description: "Generate a task header from cross-agent activity.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "task": {"type": "string"},
                "agents": {"type": "array", "items": {"type":"string"}}
            }
        }"#,
    },
    // -- personality ------------------------------------------------------
    Route {
        name: "personality.detect",
        aliases: &[],
        method: Method::Post,
        path: "/personality/detect",
        scope: Scope::Read,
        description: "Detect personality cues from a sample of text.",
        input_schema: r#"{"type": "object", "properties": {"text": {"type":"string"}}, "required": ["text"]}"#,
    },
    Route {
        name: "personality.profile",
        aliases: &[],
        method: Method::Get,
        path: "/personality/profile",
        scope: Scope::Read,
        description: "Fetch the current personality profile.",
        input_schema: r#"{"type": "object"}"#,
    },
    Route {
        name: "personality.update_profile",
        aliases: &[],
        method: Method::Post,
        path: "/personality/profile/update",
        scope: Scope::Write,
        description: "Update fields on the personality profile.",
        input_schema: r#"{"type": "object", "properties": {"traits": {"type":"object"}, "notes": {"type":"string"}}}"#,
    },
    // -- ingestion --------------------------------------------------------
    Route {
        name: "ingestion.text",
        aliases: &[],
        method: Method::Post,
        path: "/ingest",
        scope: Scope::Write,
        description: "Ingest raw text into the memory pipeline.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "text": {"type":"string"},
                "category": {"type":"string"},
                "source": {"type":"string"},
                "tags": {"type":"array","items":{"type":"string"}}
            },
            "required": ["text"]
        }"#,
    },
    Route {
        name: "ingestion.bulk",
        aliases: &[],
        method: Method::Post,
        path: "/import/bulk",
        scope: Scope::Write,
        description: "Bulk import of memories from a structured payload.",
        input_schema: r#"{"type": "object", "properties": {"items": {"type":"array"}}, "required": ["items"]}"#,
    },
    Route {
        name: "ingestion.json",
        aliases: &[],
        method: Method::Post,
        path: "/import/json",
        scope: Scope::Write,
        description: "Import memories from a JSON dump.",
        input_schema: r#"{"type": "object", "properties": {"data": {"type":"object"}}, "required": ["data"]}"#,
    },
    Route {
        name: "ingestion.upload_init",
        aliases: &[],
        method: Method::Post,
        path: "/ingest/upload/init",
        scope: Scope::Write,
        description: "Begin a chunked upload session.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "filename": {"type":"string"},
                "size": {"type":"integer"},
                "sha256": {"type":"string"},
                "mime": {"type":"string"}
            },
            "required": ["filename", "size"]
        }"#,
    },
    Route {
        name: "ingestion.upload_chunk",
        aliases: &[],
        method: Method::Post,
        path: "/ingest/upload/chunk",
        scope: Scope::Write,
        description: "Submit one chunk in a chunked upload.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "upload_id": {"type":"string"},
                "offset": {"type":"integer"},
                "data": {"type":"string","description":"base64-encoded chunk"}
            },
            "required": ["upload_id", "offset", "data"]
        }"#,
    },
    Route {
        name: "ingestion.upload_complete",
        aliases: &[],
        method: Method::Post,
        path: "/ingest/upload/complete",
        scope: Scope::Write,
        description: "Finalise a chunked upload.",
        input_schema: r#"{"type": "object", "properties": {"upload_id": {"type":"string"}}, "required": ["upload_id"]}"#,
    },
    Route {
        name: "ingestion.upload_abort",
        aliases: &[],
        method: Method::Post,
        path: "/ingest/upload/abort",
        scope: Scope::Write,
        description: "Abort a chunked upload.",
        input_schema: r#"{"type": "object", "properties": {"upload_id": {"type":"string"}}, "required": ["upload_id"]}"#,
    },
    Route {
        name: "ingestion.upload_status",
        aliases: &[],
        method: Method::Get,
        path: "/ingest/upload/{upload_id}/status",
        scope: Scope::Read,
        description: "Check status of a chunked upload.",
        input_schema: r#"{"type": "object", "properties": {"upload_id": {"type":"string"}}, "required": ["upload_id"]}"#,
    },
    // -- inbox ------------------------------------------------------------
    Route {
        name: "inbox.list",
        aliases: &[],
        method: Method::Get,
        path: "/inbox",
        scope: Scope::Read,
        description: "List pending inbox items.",
        input_schema: r#"{"type": "object", "properties": {"limit": {"type":"integer"}}}"#,
    },
    Route {
        name: "inbox.approve",
        aliases: &[],
        method: Method::Post,
        path: "/inbox/{id}/approve",
        scope: Scope::Write,
        description: "Approve an inbox item.",
        input_schema: r#"{"type": "object", "properties": {"id": {"type":"integer"}}, "required": ["id"]}"#,
    },
    Route {
        name: "inbox.reject",
        aliases: &[],
        method: Method::Post,
        path: "/inbox/{id}/reject",
        scope: Scope::Write,
        description: "Reject an inbox item.",
        input_schema: r#"{"type": "object", "properties": {"id": {"type":"integer"}, "reason": {"type":"string"}}, "required": ["id"]}"#,
    },
    Route {
        name: "inbox.edit",
        aliases: &[],
        method: Method::Post,
        path: "/inbox/{id}/edit",
        scope: Scope::Write,
        description: "Edit an inbox item before approving.",
        input_schema: r#"{"type": "object", "properties": {"id": {"type":"integer"}, "patch": {"type":"object"}}, "required": ["id", "patch"]}"#,
    },
    Route {
        name: "inbox.bulk",
        aliases: &[],
        method: Method::Post,
        path: "/inbox/bulk",
        scope: Scope::Write,
        description: "Apply an action to multiple inbox items at once.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "ids": {"type":"array","items":{"type":"integer"}},
                "action": {"type":"string"}
            },
            "required": ["ids", "action"]
        }"#,
    },
    // -- projects ---------------------------------------------------------
    Route {
        name: "projects.list",
        aliases: &[],
        method: Method::Get,
        path: "/projects",
        scope: Scope::Read,
        description: "List projects.",
        input_schema: r#"{"type": "object"}"#,
    },
    Route {
        name: "projects.create",
        aliases: &[],
        method: Method::Post,
        path: "/projects",
        scope: Scope::Write,
        description: "Create a project.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "name": {"type":"string"},
                "description": {"type":"string"}
            },
            "required": ["name"]
        }"#,
    },
    Route {
        name: "projects.get",
        aliases: &[],
        method: Method::Get,
        path: "/projects/{id}",
        scope: Scope::Read,
        description: "Fetch a project by id.",
        input_schema: r#"{"type": "object", "properties": {"id": {"type":"integer"}}, "required": ["id"]}"#,
    },
    Route {
        name: "projects.update",
        aliases: &[],
        method: Method::Put,
        path: "/projects/{id}",
        scope: Scope::Write,
        description: "Update a project.",
        input_schema: r#"{
            "type": "object",
            "properties": {
                "id": {"type":"integer"},
                "name": {"type":"string"},
                "description": {"type":"string"}
            },
            "required": ["id"]
        }"#,
    },
    Route {
        name: "projects.link_memory",
        aliases: &[],
        method: Method::Put,
        path: "/projects/{id}/memories/{mid}",
        scope: Scope::Write,
        description: "Link a memory to a project.",
        input_schema: r#"{"type": "object", "properties": {"id": {"type":"integer"}, "mid": {"type":"integer"}}, "required": ["id", "mid"]}"#,
    },
    Route {
        name: "projects.unlink_memory",
        aliases: &[],
        method: Method::Delete,
        path: "/projects/{id}/memories/{mid}",
        scope: Scope::Write,
        description: "Unlink a memory from a project.",
        input_schema: r#"{"type": "object", "properties": {"id": {"type":"integer"}, "mid": {"type":"integer"}}, "required": ["id", "mid"]}"#,
    },
    // -- approvals --------------------------------------------------------
    Route {
        name: "approvals.create",
        aliases: &[],
        method: Method::Post,
        path: "/approvals",
        scope: Scope::Write,
        description: "Submit an approval request.",
        input_schema: r#"{"type":"object","properties":{"subject":{"type":"string"},"detail":{"type":"string"},"metadata":{"type":"object"}},"required":["subject"]}"#,
    },
    Route {
        name: "approvals.list_pending",
        aliases: &[],
        method: Method::Get,
        path: "/approvals/pending",
        scope: Scope::Read,
        description: "List approvals awaiting a decision.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "approvals.get",
        aliases: &[],
        method: Method::Get,
        path: "/approvals/{id}",
        scope: Scope::Read,
        description: "Fetch one approval request.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "approvals.decide",
        aliases: &[],
        method: Method::Post,
        path: "/approvals/{id}/decide",
        scope: Scope::Write,
        description: "Approve or deny a pending approval.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"},"decision":{"type":"string","enum":["approve","deny"]},"reason":{"type":"string"}},"required":["id","decision"]}"#,
    },
    // -- audit ------------------------------------------------------------
    Route {
        name: "audit.list",
        aliases: &[],
        method: Method::Get,
        path: "/audit",
        scope: Scope::Read,
        description: "Stream audit log entries.",
        input_schema: r#"{"type":"object","properties":{"limit":{"type":"integer"},"since":{"type":"string"}}}"#,
    },
    // -- policy -----------------------------------------------------------
    Route {
        name: "policy.mandatory",
        aliases: &[],
        method: Method::Get,
        path: "/policy/mandatory",
        scope: Scope::Read,
        description: "Fetch the mandatory policy bundle.",
        input_schema: r#"{"type":"object"}"#,
    },
    // -- gate -------------------------------------------------------------
    Route {
        name: "gate.check",
        aliases: &[],
        method: Method::Post,
        path: "/gate/check",
        scope: Scope::Read,
        description: "Pre-flight a tool invocation against gate policy.",
        input_schema: r#"{"type":"object","properties":{"agent":{"type":"string"},"tool":{"type":"string"},"args":{"type":"object"}},"required":["tool"]}"#,
    },
    Route {
        name: "gate.respond",
        aliases: &[],
        method: Method::Post,
        path: "/gate/respond",
        scope: Scope::Write,
        description: "Respond to a gate prompt.",
        input_schema: r#"{"type":"object","properties":{"gate_id":{"type":"string"},"response":{"type":"string"}},"required":["gate_id","response"]}"#,
    },
    Route {
        name: "gate.complete",
        aliases: &[],
        method: Method::Post,
        path: "/gate/complete",
        scope: Scope::Write,
        description: "Mark a gate-tracked action complete.",
        input_schema: r#"{"type":"object","properties":{"gate_id":{"type":"string"},"result":{"type":"string"}}}"#,
    },
    Route {
        name: "gate.complete_latest",
        aliases: &[],
        method: Method::Post,
        path: "/gate/complete-latest",
        scope: Scope::Write,
        description: "Mark the most recent gate-tracked action complete.",
        input_schema: r#"{"type":"object","properties":{"result":{"type":"string"}}}"#,
    },
    Route {
        name: "gate.guard",
        aliases: &[],
        method: Method::Post,
        path: "/guard",
        scope: Scope::Read,
        description: "Run content against the policy guard.",
        input_schema: r#"{"type":"object","properties":{"content":{"type":"string"},"action":{"type":"string"}},"required":["content"]}"#,
    },
    // -- security ---------------------------------------------------------
    Route {
        name: "security.rate_limit",
        aliases: &[],
        method: Method::Get,
        path: "/rate-limit/{key}",
        scope: Scope::Read,
        description: "Rate-limit status for a given key.",
        input_schema: r#"{"type":"object","properties":{"key":{"type":"string"}},"required":["key"]}"#,
    },
    Route {
        name: "security.quota",
        aliases: &[],
        method: Method::Get,
        path: "/quota",
        scope: Scope::Read,
        description: "Current quota usage.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "security.record_usage",
        aliases: &[],
        method: Method::Post,
        path: "/usage",
        scope: Scope::Write,
        description: "Record a usage event against quota.",
        input_schema: r#"{"type":"object","properties":{"event":{"type":"string"},"qty":{"type":"integer"}},"required":["event"]}"#,
    },
    // -- portability ------------------------------------------------------
    Route {
        name: "portability.export",
        aliases: &[],
        method: Method::Get,
        path: "/export",
        scope: Scope::Read,
        description: "Export user data for portability.",
        input_schema: r#"{"type":"object","properties":{"format":{"type":"string"}}}"#,
    },
    Route {
        name: "portability.import",
        aliases: &[],
        method: Method::Post,
        path: "/import",
        scope: Scope::Write,
        description: "Import a portable bundle.",
        input_schema: r#"{"type":"object","properties":{"data":{"type":"object"}},"required":["data"]}"#,
    },
    // -- webhooks ---------------------------------------------------------
    Route {
        name: "webhooks.test",
        aliases: &[],
        method: Method::Post,
        path: "/webhooks/test/{id}",
        scope: Scope::Write,
        description: "Fire a test event against a registered webhook.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    // -- auth_keys --------------------------------------------------------
    Route {
        name: "auth_keys.create",
        aliases: &[],
        method: Method::Post,
        path: "/keys",
        scope: Scope::Admin,
        description: "Create an API key.",
        input_schema: r#"{"type":"object","properties":{"name":{"type":"string"},"scopes":{"type":"array","items":{"type":"string"}}},"required":["name","scopes"]}"#,
    },
    Route {
        name: "auth_keys.list",
        aliases: &[],
        method: Method::Get,
        path: "/keys",
        scope: Scope::Read,
        description: "List API keys.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "auth_keys.revoke",
        aliases: &[],
        method: Method::Delete,
        path: "/keys/{id}",
        scope: Scope::Admin,
        description: "Revoke an API key.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "auth_keys.rotate",
        aliases: &[],
        method: Method::Post,
        path: "/keys/rotate",
        scope: Scope::Admin,
        description: "Rotate an API key.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "auth_keys.create_space",
        aliases: &[],
        method: Method::Post,
        path: "/spaces",
        scope: Scope::Admin,
        description: "Create a memory space.",
        input_schema: r#"{"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}"#,
    },
    Route {
        name: "auth_keys.list_spaces",
        aliases: &[],
        method: Method::Get,
        path: "/spaces",
        scope: Scope::Read,
        description: "List memory spaces.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "auth_keys.delete_space",
        aliases: &[],
        method: Method::Delete,
        path: "/spaces/{id}",
        scope: Scope::Admin,
        description: "Delete a memory space.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    // -- identities -------------------------------------------------------
    Route {
        name: "identities.list",
        aliases: &[],
        method: Method::Get,
        path: "/identities",
        scope: Scope::Read,
        description: "List enrolled identities.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "identities.audit",
        aliases: &[],
        method: Method::Get,
        path: "/identities/{id}/audit",
        scope: Scope::Read,
        description: "Per-identity audit trail.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    // -- identity_keys ----------------------------------------------------
    Route {
        name: "identity_keys.enroll",
        aliases: &[],
        method: Method::Post,
        path: "/identity-keys/enroll",
        scope: Scope::Write,
        description: "Enroll a new identity key (PIV/Ed25519).",
        input_schema: r#"{"type":"object","properties":{"pubkey_pem":{"type":"string"},"label":{"type":"string"},"sig_hex":{"type":"string"}},"required":["pubkey_pem"]}"#,
    },
    Route {
        name: "identity_keys.list",
        aliases: &[],
        method: Method::Get,
        path: "/identity-keys",
        scope: Scope::Read,
        description: "List all identity keys (admin view).",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "identity_keys.mine",
        aliases: &[],
        method: Method::Get,
        path: "/identity-keys/mine",
        scope: Scope::Read,
        description: "List the caller's own identity keys.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "identity_keys.revoke",
        aliases: &[],
        method: Method::Post,
        path: "/identity-keys/{id}/revoke",
        scope: Scope::Write,
        description: "Revoke an identity key.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "identity_keys.invite",
        aliases: &[],
        method: Method::Post,
        path: "/identity-keys/invite",
        scope: Scope::Admin,
        description: "Issue an invite for identity-key enrollment.",
        input_schema: r#"{"type":"object","properties":{"label":{"type":"string"},"ttl_seconds":{"type":"integer"}}}"#,
    },
    // -- agents -----------------------------------------------------------
    Route {
        name: "agents.register",
        aliases: &[],
        method: Method::Post,
        path: "/agents",
        scope: Scope::Write,
        description: "Register a new agent.",
        input_schema: r#"{"type":"object","properties":{"name":{"type":"string"},"agent_type":{"type":"string"},"description":{"type":"string"},"capabilities":{"type":"array","items":{"type":"string"}},"config":{"type":"object"}},"required":["name"]}"#,
    },
    Route {
        name: "agents.list",
        aliases: &[],
        method: Method::Get,
        path: "/agents",
        scope: Scope::Read,
        description: "List registered agents.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "agents.get",
        aliases: &[],
        method: Method::Get,
        path: "/agents/{id}",
        scope: Scope::Read,
        description: "Fetch an agent record.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "agents.revoke",
        aliases: &[],
        method: Method::Post,
        path: "/agents/{id}/revoke",
        scope: Scope::Admin,
        description: "Revoke an agent.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "agents.passport",
        aliases: &[],
        method: Method::Get,
        path: "/agents/{id}/passport",
        scope: Scope::Read,
        description: "Fetch an agent's passport bundle.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "agents.link_key",
        aliases: &[],
        method: Method::Post,
        path: "/agents/{id}/link-key",
        scope: Scope::Write,
        description: "Link an identity key to an agent.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"},"key_id":{"type":"integer"}},"required":["id","key_id"]}"#,
    },
    Route {
        name: "agents.executions",
        aliases: &[],
        method: Method::Get,
        path: "/agents/{id}/executions",
        scope: Scope::Read,
        description: "List an agent's recorded executions.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"},"limit":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "agents.verify",
        aliases: &[],
        method: Method::Post,
        path: "/verify",
        scope: Scope::Write,
        description: "Verify a code change against the spec (agent-forge verify).",
        input_schema: r#"{"type":"object","properties":{"spec_id":{"type":"string"},"steps":{"type":"array"}}}"#,
    },
    // -- conversations ----------------------------------------------------
    Route {
        name: "conversations.create",
        aliases: &[],
        method: Method::Post,
        path: "/conversations",
        scope: Scope::Write,
        description: "Create a conversation thread.",
        input_schema: r#"{"type":"object","properties":{"title":{"type":"string"},"metadata":{"type":"object"}}}"#,
    },
    Route {
        name: "conversations.list",
        aliases: &[],
        method: Method::Get,
        path: "/conversations",
        scope: Scope::Read,
        description: "List conversation threads.",
        input_schema: r#"{"type":"object","properties":{"limit":{"type":"integer"}}}"#,
    },
    Route {
        name: "conversations.add_message",
        aliases: &[],
        method: Method::Post,
        path: "/conversations/{id}/messages",
        scope: Scope::Write,
        description: "Append a message to a conversation.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"},"role":{"type":"string"},"content":{"type":"string"}},"required":["id","content"]}"#,
    },
    Route {
        name: "conversations.list_messages",
        aliases: &[],
        method: Method::Get,
        path: "/conversations/{id}/messages",
        scope: Scope::Read,
        description: "List messages in a conversation.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"},"limit":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "conversations.search_messages",
        aliases: &[],
        method: Method::Post,
        path: "/messages/search",
        scope: Scope::Read,
        description: "Search across conversation messages.",
        input_schema: r#"{"type":"object","properties":{"query":{"type":"string"},"limit":{"type":"integer"}},"required":["query"]}"#,
    },
    // -- errors -----------------------------------------------------------
    Route {
        name: "errors.report",
        aliases: &[],
        method: Method::Post,
        path: "/errors",
        scope: Scope::Write,
        description: "Report an agent error event.",
        input_schema: r#"{"type":"object","properties":{"agent":{"type":"string"},"message":{"type":"string"},"context":{"type":"object"}},"required":["message"]}"#,
    },
    Route {
        name: "errors.list",
        aliases: &[],
        method: Method::Get,
        path: "/errors",
        scope: Scope::Read,
        description: "List recently reported errors.",
        input_schema: r#"{"type":"object","properties":{"limit":{"type":"integer"}}}"#,
    },
    // -- supervisor -------------------------------------------------------
    Route {
        name: "supervisor.inject",
        aliases: &[],
        method: Method::Post,
        path: "/supervisor/inject",
        scope: Scope::Write,
        description: "Inject a supervisor directive.",
        input_schema: r#"{"type":"object","properties":{"agent":{"type":"string"},"directive":{"type":"string"}},"required":["directive"]}"#,
    },
    Route {
        name: "supervisor.pending",
        aliases: &[],
        method: Method::Get,
        path: "/supervisor/pending",
        scope: Scope::Read,
        description: "List pending supervisor directives.",
        input_schema: r#"{"type":"object"}"#,
    },
    // -- brain (Hopfield) -------------------------------------------------
    Route {
        name: "brain.stats",
        aliases: &[],
        method: Method::Get,
        path: "/brain/stats",
        scope: Scope::Read,
        description: "Hopfield-network capacity / activation stats.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "brain.query",
        aliases: &[],
        method: Method::Post,
        path: "/brain/query",
        scope: Scope::Read,
        description: "Query the Hopfield brain with a partial cue.",
        input_schema: r#"{"type":"object","properties":{"cue":{"type":"string"},"limit":{"type":"integer"}},"required":["cue"]}"#,
    },
    Route {
        name: "brain.absorb",
        aliases: &[],
        method: Method::Post,
        path: "/brain/absorb",
        scope: Scope::Write,
        description: "Absorb a new pattern into the Hopfield brain.",
        input_schema: r#"{"type":"object","properties":{"pattern":{"type":"string"},"weight":{"type":"number"}},"required":["pattern"]}"#,
    },
    Route {
        name: "brain.dream",
        aliases: &[],
        method: Method::Post,
        path: "/brain/dream",
        scope: Scope::Write,
        description: "Trigger an offline consolidation pass.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "brain.feedback",
        aliases: &[],
        method: Method::Post,
        path: "/brain/feedback",
        scope: Scope::Write,
        description: "Provide feedback on a Hopfield recall.",
        input_schema: r#"{"type":"object","properties":{"pattern":{"type":"string"},"rating":{"type":"integer"}},"required":["pattern","rating"]}"#,
    },
    Route {
        name: "brain.decay",
        aliases: &[],
        method: Method::Post,
        path: "/brain/decay",
        scope: Scope::Admin,
        description: "Apply a decay sweep to stored patterns.",
        input_schema: r#"{"type":"object","properties":{"factor":{"type":"number"}}}"#,
    },
    Route {
        name: "brain.evolution_train",
        aliases: &[],
        method: Method::Post,
        path: "/brain/evolution/train",
        scope: Scope::Admin,
        description: "Run the brain's evolutionary training cycle.",
        input_schema: r#"{"type":"object","properties":{"iterations":{"type":"integer"}}}"#,
    },
    Route {
        name: "brain.evolution_stats",
        aliases: &[],
        method: Method::Get,
        path: "/brain/evolution/stats",
        scope: Scope::Read,
        description: "Brain evolutionary training stats.",
        input_schema: r#"{"type":"object"}"#,
    },
    // -- graph (knowledge graph) -----------------------------------------
    Route {
        name: "graph.entity_memories",
        aliases: &[],
        method: Method::Get,
        path: "/entities/{id}/memories",
        scope: Scope::Read,
        description: "List memories linked to an entity.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "graph.entity_search",
        aliases: &[],
        method: Method::Post,
        path: "/entities/{id}/search",
        scope: Scope::Read,
        description: "Search within the neighborhood of an entity.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"},"query":{"type":"string"}},"required":["id","query"]}"#,
    },
    Route {
        name: "graph.create_relationship",
        aliases: &[],
        method: Method::Post,
        path: "/entity-relationships",
        scope: Scope::Write,
        description: "Create an entity-to-entity relationship.",
        input_schema: r#"{"type":"object","properties":{"source_id":{"type":"integer"},"target_id":{"type":"integer"},"rel_type":{"type":"string"}},"required":["source_id","target_id","rel_type"]}"#,
    },
    Route {
        name: "graph.view",
        aliases: &[],
        method: Method::Get,
        path: "/graph",
        scope: Scope::Read,
        description: "Default graph view.",
        input_schema: r#"{"type":"object","properties":{"limit":{"type":"integer"}}}"#,
    },
    Route {
        name: "graph.raw",
        aliases: &[],
        method: Method::Get,
        path: "/graph/raw",
        scope: Scope::Read,
        description: "Raw graph dump (nodes + edges).",
        input_schema: r#"{"type":"object","properties":{"limit":{"type":"integer"}}}"#,
    },
    Route {
        name: "graph.build",
        aliases: &[],
        method: Method::Post,
        path: "/graph/build",
        scope: Scope::Admin,
        description: "Rebuild the graph from current memories.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "graph.search",
        aliases: &[],
        method: Method::Post,
        path: "/graph/search",
        scope: Scope::Read,
        description: "Search the graph for entities / paths.",
        input_schema: r#"{"type":"object","properties":{"query":{"type":"string"},"depth":{"type":"integer"}},"required":["query"]}"#,
    },
    // -- intelligence -----------------------------------------------------
    Route {
        name: "intelligence.consolidate",
        aliases: &[],
        method: Method::Post,
        path: "/intelligence/consolidate",
        scope: Scope::Write,
        description: "Consolidate a set of memories into a composite.",
        input_schema: r#"{"type":"object","properties":{"memory_ids":{"type":"array","items":{"type":"integer"}}},"required":["memory_ids"]}"#,
    },
    Route {
        name: "intelligence.contradictions",
        aliases: &[],
        method: Method::Get,
        path: "/contradictions/{memory_id}",
        scope: Scope::Read,
        description: "Find contradictions for a single memory.",
        input_schema: r#"{"type":"object","properties":{"memory_id":{"type":"integer"}},"required":["memory_id"]}"#,
    },
    Route {
        name: "intelligence.scan_contradictions",
        aliases: &[],
        method: Method::Post,
        path: "/contradictions",
        scope: Scope::Read,
        description: "Account-wide scan for contradictions.",
        input_schema: r#"{"type":"object","properties":{"limit":{"type":"integer"}}}"#,
    },
    Route {
        name: "intelligence.generate_digest",
        aliases: &[],
        method: Method::Post,
        path: "/digests/generate",
        scope: Scope::Write,
        description: "Generate a memory digest.",
        input_schema: r#"{"type":"object","properties":{"window":{"type":"string"}}}"#,
    },
    Route {
        name: "intelligence.list_digests",
        aliases: &[],
        method: Method::Get,
        path: "/intelligence/digests",
        scope: Scope::Read,
        description: "List previously generated digests.",
        input_schema: r#"{"type":"object","properties":{"limit":{"type":"integer"}}}"#,
    },
    Route {
        name: "intelligence.reflect",
        aliases: &[],
        method: Method::Post,
        path: "/reflect",
        scope: Scope::Write,
        description: "Create a reflection record.",
        input_schema: r#"{"type":"object","properties":{"reflection_type":{"type":"string"},"summary":{"type":"string"},"refs":{"type":"array","items":{"type":"integer"}}},"required":["summary"]}"#,
    },
    // -- admin ------------------------------------------------------------
    Route {
        name: "admin.bootstrap",
        aliases: &[],
        method: Method::Post,
        path: "/bootstrap",
        scope: Scope::Admin,
        description: "Run the admin bootstrap routine.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "admin.stats",
        aliases: &[],
        method: Method::Get,
        path: "/stats",
        scope: Scope::Read,
        description: "Server-wide stats.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "admin.get_settings",
        aliases: &[],
        method: Method::Get,
        path: "/admin/settings",
        scope: Scope::Admin,
        description: "Fetch server settings.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "admin.put_settings",
        aliases: &[],
        method: Method::Put,
        path: "/admin/settings",
        scope: Scope::Admin,
        description: "Update server settings.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "admin.gc",
        aliases: &[],
        method: Method::Post,
        path: "/admin/gc",
        scope: Scope::Admin,
        description: "Run a garbage-collection sweep.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "admin.compact",
        aliases: &[],
        method: Method::Post,
        path: "/admin/compact",
        scope: Scope::Admin,
        description: "Compact (VACUUM) the database.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "admin.reembed",
        aliases: &[],
        method: Method::Post,
        path: "/admin/reembed",
        scope: Scope::Admin,
        description: "Re-embed memories with the current model.",
        input_schema: r#"{"type":"object","properties":{"all":{"type":"boolean"}}}"#,
    },
    Route {
        name: "admin.rebuild_fts",
        aliases: &[],
        method: Method::Post,
        path: "/admin/rebuild-fts",
        scope: Scope::Admin,
        description: "Rebuild the full-text-search index.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "admin.refresh_cache",
        aliases: &[],
        method: Method::Post,
        path: "/admin/refresh-cache",
        scope: Scope::Admin,
        description: "Refresh the in-memory caches.",
        input_schema: r#"{"type":"object"}"#,
    },
    // -- skills (additional richer endpoints) -----------------------------
    Route {
        name: "skills.sync",
        aliases: &[],
        method: Method::Post,
        path: "/skills/sync",
        scope: Scope::Write,
        description: "Bulk-sync skills from a source.",
        input_schema: r#"{"type":"object","properties":{"items":{"type":"array"}},"required":["items"]}"#,
    },
    Route {
        name: "skills.update",
        aliases: &[],
        method: Method::Post,
        path: "/skills/{id}/update",
        scope: Scope::Write,
        description: "Update a skill record.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"},"patch":{"type":"object"}},"required":["id","patch"]}"#,
    },
    Route {
        name: "skills.recompute",
        aliases: &[],
        method: Method::Post,
        path: "/skills/{id}/recompute",
        scope: Scope::Write,
        description: "Recompute scores for a skill.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "skills.record_execution",
        aliases: &[],
        method: Method::Post,
        path: "/skills/{id}/execute",
        scope: Scope::Write,
        description: "Record a skill execution outcome.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"},"success":{"type":"boolean"},"notes":{"type":"string"}},"required":["id","success"]}"#,
    },
    Route {
        name: "skills.list_executions",
        aliases: &[],
        method: Method::Get,
        path: "/skills/{id}/executions",
        scope: Scope::Read,
        description: "List a skill's prior executions.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"},"limit":{"type":"integer"}},"required":["id"]}"#,
    },
    // -- context (8-layer assembly) ---------------------------------------
    Route {
        name: "context.build",
        aliases: &["context.assemble_context"],
        method: Method::Post,
        path: "/context",
        scope: Scope::Read,
        description: "Build an 8-layer context bundle for a task.",
        input_schema: r#"{"type":"object","properties":{"task":{"type":"string"},"limit":{"type":"integer"}},"required":["task"]}"#,
    },
    Route {
        name: "context.build_stream",
        aliases: &[],
        method: Method::Post,
        path: "/context/stream",
        scope: Scope::Read,
        description: "Streamed context-build endpoint.",
        input_schema: r#"{"type":"object","properties":{"task":{"type":"string"}},"required":["task"]}"#,
    },
    // -- artifacts --------------------------------------------------------
    Route {
        name: "artifacts.stats",
        aliases: &[],
        method: Method::Get,
        path: "/artifacts/stats",
        scope: Scope::Read,
        description: "Aggregate artifact-store statistics.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "artifacts.download",
        aliases: &[],
        method: Method::Get,
        path: "/artifact/{id}",
        scope: Scope::Read,
        description: "Download an artifact by id.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]}"#,
    },
    // -- axon (events) ----------------------------------------------------
    Route {
        name: "axon.publish",
        aliases: &["services.axon_publish"],
        method: Method::Post,
        path: "/axon/publish",
        scope: Scope::Write,
        description: "Publish an event to Axon.",
        input_schema: r#"{"type":"object","properties":{"channel":{"type":"string"},"action":{"type":"string"},"payload":{"type":"object"},"source":{"type":"string"},"agent":{"type":"string"}},"required":["channel","action"]}"#,
    },
    Route {
        name: "axon.list_events",
        aliases: &["services.axon_consume"],
        method: Method::Get,
        path: "/axon/events",
        scope: Scope::Read,
        description: "List Axon events.",
        input_schema: r#"{"type":"object","properties":{"channel":{"type":"string"},"limit":{"type":"integer"},"since":{"type":"string"}}}"#,
    },
    Route {
        name: "axon.get_event",
        aliases: &[],
        method: Method::Get,
        path: "/axon/events/{id}",
        scope: Scope::Read,
        description: "Fetch one Axon event.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "axon.list_subscriptions",
        aliases: &[],
        method: Method::Get,
        path: "/axon/subscriptions",
        scope: Scope::Read,
        description: "List Axon subscriptions.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "axon.poll",
        aliases: &[],
        method: Method::Post,
        path: "/axon/poll",
        scope: Scope::Read,
        description: "Long-poll an Axon channel for new events.",
        input_schema: r#"{"type":"object","properties":{"channel":{"type":"string"},"cursor":{"type":"string"}},"required":["channel"]}"#,
    },
    Route {
        name: "axon.cursor",
        aliases: &[],
        method: Method::Get,
        path: "/axon/cursor",
        scope: Scope::Read,
        description: "Get the current Axon cursor.",
        input_schema: r#"{"type":"object","properties":{"channel":{"type":"string"}}}"#,
    },
    Route {
        name: "axon.stats",
        aliases: &[],
        method: Method::Get,
        path: "/axon/stats",
        scope: Scope::Read,
        description: "Axon channel statistics.",
        input_schema: r#"{"type":"object"}"#,
    },
    // -- broca (actions) --------------------------------------------------
    Route {
        name: "broca.get_action",
        aliases: &[],
        method: Method::Get,
        path: "/broca/actions/{id}",
        scope: Scope::Read,
        description: "Fetch one Broca action record.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "broca.feed",
        aliases: &[],
        method: Method::Get,
        path: "/broca/feed",
        scope: Scope::Read,
        description: "Live feed of Broca-logged actions.",
        input_schema: r#"{"type":"object","properties":{"limit":{"type":"integer"}}}"#,
    },
    Route {
        name: "broca.stats",
        aliases: &[],
        method: Method::Get,
        path: "/broca/stats",
        scope: Scope::Read,
        description: "Broca action statistics.",
        input_schema: r#"{"type":"object"}"#,
    },
    // -- soma (agent presence) --------------------------------------------
    Route {
        name: "soma.heartbeat",
        aliases: &["services.soma_heartbeat"],
        method: Method::Post,
        path: "/soma/agents/{id}/heartbeat",
        scope: Scope::Write,
        description: "Agent keepalive heartbeat.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "soma.list_logs",
        aliases: &[],
        method: Method::Get,
        path: "/soma/agents/{id}/logs",
        scope: Scope::Read,
        description: "Recent Soma log entries for an agent.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"},"limit":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "soma.add_group_member",
        aliases: &[],
        method: Method::Post,
        path: "/soma/groups/{id}/members",
        scope: Scope::Write,
        description: "Add an agent to a Soma group.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"},"agent_id":{"type":"integer"}},"required":["id","agent_id"]}"#,
    },
    Route {
        name: "soma.stats",
        aliases: &[],
        method: Method::Get,
        path: "/soma/stats",
        scope: Scope::Read,
        description: "Soma presence statistics.",
        input_schema: r#"{"type":"object"}"#,
    },
    // -- thymus (evaluation) ----------------------------------------------
    Route {
        name: "thymus.evaluate",
        aliases: &["services.thymus_review"],
        method: Method::Post,
        path: "/thymus/evaluate",
        scope: Scope::Write,
        description: "Record an evaluation outcome.",
        input_schema: r#"{"type":"object","properties":{"rubric_id":{"type":"integer"},"agent":{"type":"string"},"subject":{"type":"string"},"scores":{"type":"object"}},"required":["rubric_id","agent","subject","scores"]}"#,
    },
    Route {
        name: "thymus.list_evaluations",
        aliases: &[],
        method: Method::Get,
        path: "/thymus/evaluations",
        scope: Scope::Read,
        description: "List evaluation records.",
        input_schema: r#"{"type":"object","properties":{"limit":{"type":"integer"}}}"#,
    },
    Route {
        name: "thymus.get_evaluation",
        aliases: &[],
        method: Method::Get,
        path: "/thymus/evaluations/{id}",
        scope: Scope::Read,
        description: "Fetch one evaluation record.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "thymus.metric_summary",
        aliases: &[],
        method: Method::Get,
        path: "/thymus/metrics/summary",
        scope: Scope::Read,
        description: "Aggregate metric summary.",
        input_schema: r#"{"type":"object","properties":{"window":{"type":"string"}}}"#,
    },
    Route {
        name: "thymus.stats",
        aliases: &[],
        method: Method::Get,
        path: "/thymus/stats",
        scope: Scope::Read,
        description: "Thymus evaluation statistics.",
        input_schema: r#"{"type":"object"}"#,
    },
    // -- growth -----------------------------------------------------------
    Route {
        name: "growth.reflect",
        aliases: &[],
        method: Method::Post,
        path: "/growth/reflect",
        scope: Scope::Write,
        description: "Record a growth-reflection note.",
        input_schema: r#"{"type":"object","properties":{"observation":{"type":"string"},"context":{"type":"string"}},"required":["observation"]}"#,
    },
    Route {
        name: "growth.observations",
        aliases: &[],
        method: Method::Get,
        path: "/growth/observations",
        scope: Scope::Read,
        description: "List growth observations.",
        input_schema: r#"{"type":"object","properties":{"limit":{"type":"integer"}}}"#,
    },
    Route {
        name: "growth.materialize",
        aliases: &[],
        method: Method::Post,
        path: "/growth/materialize",
        scope: Scope::Write,
        description: "Materialise growth notes into durable memory.",
        input_schema: r#"{"type":"object","properties":{"ids":{"type":"array","items":{"type":"integer"}}}}"#,
    },
    // -- commerce ---------------------------------------------------------
    Route {
        name: "commerce.create_quote",
        aliases: &[],
        method: Method::Post,
        path: "/commerce/quotes",
        scope: Scope::Write,
        description: "Create a commerce quote.",
        input_schema: r#"{"type":"object","properties":{"item":{"type":"string"},"qty":{"type":"integer"}},"required":["item"]}"#,
    },
    Route {
        name: "commerce.get_quote",
        aliases: &[],
        method: Method::Get,
        path: "/commerce/quotes/{id}",
        scope: Scope::Read,
        description: "Fetch a commerce quote.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "commerce.budget_check",
        aliases: &[],
        method: Method::Post,
        path: "/commerce/check",
        scope: Scope::Read,
        description: "Pre-flight a spend against budget.",
        input_schema: r#"{"type":"object","properties":{"amount":{"type":"number"},"currency":{"type":"string"}},"required":["amount"]}"#,
    },
    Route {
        name: "commerce.reconciliation",
        aliases: &[],
        method: Method::Get,
        path: "/commerce/reconciliation",
        scope: Scope::Read,
        description: "Fetch the latest reconciliation report.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "commerce.balance",
        aliases: &[],
        method: Method::Get,
        path: "/commerce/balance",
        scope: Scope::Read,
        description: "Fetch the current balance.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "commerce.pricing",
        aliases: &[],
        method: Method::Get,
        path: "/commerce/pricing",
        scope: Scope::Read,
        description: "List pricing tables.",
        input_schema: r#"{"type":"object"}"#,
    },
    // -- loom (workflows) -------------------------------------------------
    Route {
        name: "loom.get_run",
        aliases: &[],
        method: Method::Get,
        path: "/loom/runs/{id}",
        scope: Scope::Read,
        description: "Fetch one Loom run.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "loom.cancel_run",
        aliases: &[],
        method: Method::Post,
        path: "/loom/runs/{id}/cancel",
        scope: Scope::Write,
        description: "Cancel a running Loom workflow.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "loom.get_steps",
        aliases: &[],
        method: Method::Get,
        path: "/loom/runs/{id}/steps",
        scope: Scope::Read,
        description: "List a run's steps.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "loom.get_logs",
        aliases: &[],
        method: Method::Get,
        path: "/loom/runs/{id}/logs",
        scope: Scope::Read,
        description: "Fetch the log lines for a run.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"},"limit":{"type":"integer"}},"required":["id"]}"#,
    },
    Route {
        name: "loom.complete_step",
        aliases: &[],
        method: Method::Post,
        path: "/loom/steps/{id}/complete",
        scope: Scope::Write,
        description: "Mark a step complete.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"},"output":{"type":"object"}},"required":["id"]}"#,
    },
    Route {
        name: "loom.fail_step",
        aliases: &[],
        method: Method::Post,
        path: "/loom/steps/{id}/fail",
        scope: Scope::Write,
        description: "Mark a step failed.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"},"reason":{"type":"string"}},"required":["id"]}"#,
    },
    Route {
        name: "loom.stats",
        aliases: &[],
        method: Method::Get,
        path: "/loom/stats",
        scope: Scope::Read,
        description: "Loom workflow statistics.",
        input_schema: r#"{"type":"object"}"#,
    },
    // -- pack -------------------------------------------------------------
    Route {
        name: "pack.memories",
        aliases: &[],
        method: Method::Post,
        path: "/pack",
        scope: Scope::Read,
        description: "Pack a memory set into a portable bundle.",
        input_schema: r#"{"type":"object","properties":{"memory_ids":{"type":"array","items":{"type":"integer"}},"format":{"type":"string"}},"required":["memory_ids"]}"#,
    },
    // -- onboard ----------------------------------------------------------
    Route {
        name: "onboard.run",
        aliases: &[],
        method: Method::Post,
        path: "/onboard",
        scope: Scope::Write,
        description: "Run the onboarding routine.",
        input_schema: r#"{"type":"object","properties":{"profile":{"type":"object"}}}"#,
    },
    Route {
        name: "onboard.fetch_url",
        aliases: &[],
        method: Method::Post,
        path: "/fetch",
        scope: Scope::Write,
        description: "Fetch a URL during onboarding.",
        input_schema: r#"{"type":"object","properties":{"url":{"type":"string"}},"required":["url"]}"#,
    },
    // -- grounding --------------------------------------------------------
    Route {
        name: "grounding.list_tools",
        aliases: &[],
        method: Method::Get,
        path: "/grounding/tools",
        scope: Scope::Read,
        description: "List grounding tools.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "grounding.execute",
        aliases: &[],
        method: Method::Post,
        path: "/grounding/execute",
        scope: Scope::Write,
        description: "Execute a grounding tool.",
        input_schema: r#"{"type":"object","properties":{"tool":{"type":"string"},"args":{"type":"object"}},"required":["tool"]}"#,
    },
    Route {
        name: "grounding.quality",
        aliases: &[],
        method: Method::Get,
        path: "/grounding/quality",
        scope: Scope::Read,
        description: "Grounding quality metrics.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "grounding.list_providers",
        aliases: &[],
        method: Method::Get,
        path: "/grounding/providers",
        scope: Scope::Read,
        description: "List available grounding providers.",
        input_schema: r#"{"type":"object"}"#,
    },
    // -- batch ------------------------------------------------------------
    Route {
        name: "batch.run",
        aliases: &[],
        method: Method::Post,
        path: "/batch",
        scope: Scope::Write,
        description: "Run a batch of inline requests in one call.",
        input_schema: r#"{"type":"object","properties":{"requests":{"type":"array"}},"required":["requests"]}"#,
    },
    // -- dispatch ---------------------------------------------------------
    Route {
        name: "dispatch.list_configs",
        aliases: &[],
        method: Method::Get,
        path: "/dispatch/configs",
        scope: Scope::Read,
        description: "List dispatch configurations.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "dispatch.create_config",
        aliases: &[],
        method: Method::Post,
        path: "/dispatch/configs",
        scope: Scope::Write,
        description: "Create a dispatch configuration.",
        input_schema: r#"{"type":"object","properties":{"name":{"type":"string"},"config":{"type":"object"}},"required":["name","config"]}"#,
    },
    // -- mcp_schema -------------------------------------------------------
    Route {
        name: "mcp_schema.get",
        aliases: &[],
        method: Method::Get,
        path: "/mcp/schema",
        scope: Scope::Read,
        description: "Fetch the MCP-flavoured schema descriptor.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "mcp_schema.dispatch",
        aliases: &[],
        method: Method::Post,
        path: "/mcp/dispatch",
        scope: Scope::Write,
        description: "Server-side MCP-style dispatch.",
        input_schema: r#"{"type":"object","properties":{"tool":{"type":"string"},"arguments":{"type":"object"}},"required":["tool"]}"#,
    },
    // -- schema (discovery) -----------------------------------------------
    Route {
        name: "schema.index",
        aliases: &[],
        method: Method::Get,
        path: "/schema",
        scope: Scope::Read,
        description: "Top-level schema index.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "schema.memory",
        aliases: &[],
        method: Method::Get,
        path: "/schema/memory",
        scope: Scope::Read,
        description: "Memory schema.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "schema.services",
        aliases: &[],
        method: Method::Get,
        path: "/schema/services",
        scope: Scope::Read,
        description: "Coordination services schema.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "schema.graph",
        aliases: &[],
        method: Method::Get,
        path: "/schema/graph",
        scope: Scope::Read,
        description: "Graph schema.",
        input_schema: r#"{"type":"object"}"#,
    },
    // -- users ------------------------------------------------------------
    Route {
        name: "users.create",
        aliases: &[],
        method: Method::Post,
        path: "/users",
        scope: Scope::Admin,
        description: "Create a user.",
        input_schema: r#"{"type":"object","properties":{"username":{"type":"string"},"email":{"type":"string"},"role":{"type":"string"}},"required":["username"]}"#,
    },
    Route {
        name: "users.list",
        aliases: &[],
        method: Method::Get,
        path: "/users",
        scope: Scope::Admin,
        description: "List users.",
        input_schema: r#"{"type":"object"}"#,
    },
    Route {
        name: "users.deactivate",
        aliases: &[],
        method: Method::Delete,
        path: "/users/{id}",
        scope: Scope::Admin,
        description: "Deactivate a user account.",
        input_schema: r#"{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}"#,
    },
];
